// Generated by branding/lib/apply-branding.mjs — do not edit by hand.
//
// Active brand: agent-relay. Regenerate with: npm run branding:apply -- --brand <id>
enum Brand {
    static let productName = "Agent Relay"
    static let shortName = "Agent Relay"
    static let bundleIdentifier = "com.agentrelay.recorder"
    static let supportURL = "https://agentrelay.com"
}
