// Generated by branding/lib/apply-branding.mjs — do not edit by hand.
//
// Active brand: relayscribe. Regenerate with: npm run branding:apply -- --brand <id>
enum Brand {
    static let productName = "Relayscribe"
    static let shortName = "Relayscribe"
    static let bundleIdentifier = "com.agentrelay.relayscribe"
    static let supportURL = "https://agentrelay.com"
}
